### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by jannelie**
Restructure is done.
Save will be fixt later on. First we need the restructured code.
There is an issue for teh save.
Somebody review please?
<organisation

### CODE REVIEW

**Comment by lvdoorn** [comment]
Apparently the Travis CI build fails due to an exception caused by the timer. Please do look into this before merging.

<review

**Comment by mboom** [comment]
All test and timer issues are fixed now. The Travis build succeeded, the maven site reports no errors or warnings and will be uploaded soon by the site-maven-plugin. The new report will be visible at: http://mboom.github.io/TI2206/ in 15 minutes.

**Comment by mboom** [comment]
The new maven site report is finished and available.

**Comment by jannelie** [comment]
looks great, thanks for helping to solve these bugs <review

**Comment by msimidzioski-1** [comment]
Prima !

**Pull request merged**
