### PR TITLE
Observer pattern

### PR DESCRIPTION
**Pull request by msimidzioski-1**
Observation pattern implemented <organisation

### CODE REVIEW

**Comment by lvdoorn** [comment]
Looks good. Please do add some commentary for the score class, including the fact that it is a Singleton.

**Comment by mboom** [comment]
Please fix the warnings of unused imports adn attributes. And there are also some Checkstyle warnings,.

**Comment by mboom** [comment]
gamelogic\Game.java:217: warning: no @param for b
FingBugs: 11 bugs, against 8 bugs in the master, so the number of bugs is increased
Checkstyle warnings: 20
PMD: 1 violation
Please run maven site and check the warnings of FindBugs, CheckStyle and PMD before merging this branch. (You can view the new site already in Eclipse when the site-maven-plugin starts to run. This plugin just uploads the new site files and does not change the content of it anymore)

**Comment by mboom** [comment]
Also, I don't see any tests for the Score class. Please provide some tests or documentation why this class is not tested.

**Comment by mboom** [comment]
This is a good improvement, but still not finished.
Please test also the updateScore methods and the observer structure. This will increase the coverage and quality.

**Comment by mboom** [comment]
Also the following warnings are still not fixed:
gamelogic\Game.java:217: warning: no @param for b
FindBugs: 11 bugs
Checkstyle: 13 warnings
PMD: 1 violation
Please check maven site to view detailed information about these warnings. See README.md if maven site fails.

**Comment by mboom** [comment]
It seems I am going to need some of this code. Is there already some documentation? If the diagrams are final versions, generate them also as pdf or image. It will be easier for me to adapt the design of the level strategies so everything will be connected in a correct way.

**Comment by mboom** [comment]
Alright, Checkstyle, Javadoc and PMD warnings are solved. A couple of FindBugs warnings are solved. There are still 8 bugs left.
There are 2 kinds of bugs: ... may expose internal representation by ... For this kind of bugs there is an issue. We will later what to do with these bugs.
The other bug type: defines non-transient non-serializable instance field
Serializables are used by the old safe methods. A new save method is designed in an another branch, so there should these kind of bugs solved.

**Pull request merged**
