### PR TITLE
refactoring of gui methods in game < organization

### PR DESCRIPTION
**Pull request by msimidzioski**

### CODE REVIEW

**Comment by mboom** [comment]
Please fix the following warnings:
gamelogic\Game.java:146: warning: no @param for b
gamelogic\GameGuiMethods.java:33: warning: no description for @param
gamelogic\GameGuiMethods.java:34: warning: no description for @param
gamelogic\GameGuiMethods.java:23: warning: no @param for game1
Check unused attributes, imports and Checkstyle warnings
Findbugs: 11 bugs
Checkstyle: 9 warnings
PMD: 1 violation
Please run maven site and check the warnings of FindBugs, CheckStyle and PMD before merging this branch. (You can view the new site already in Eclipse when the site-maven-plugin starts to run. This plugin just uploads the new site files and does not change the content of it anymore)

**Comment by mboom** [comment]
Probably a couple of warnings will be solved if the merge conflicts are correctly resolved. So please rerun maven site after the merge conflicts are solved.

**Comment by mboom** [comment]
It seems I am going to need some of this code. Is there already some documentation? If the diagrams are final versions, generate them also as pdf or image. It will be easier for me to adapt the design of the level strategies so everything will be connected in a correct way.

**Comment by mboom** [comment]
Checkstyle, Javadoc and PMD warnings are solved. A couple of FindBugs warnings are solved. There are still 8 bugs left.
There are 2 kinds of bugs: ... may expose internal representation by ... For this kind of bugs there is an issue. We will later what to do with these bugs.
The other bug type: defines non-transient non-serializable instance field
Serializables are used by the old safe methods. A new save method is designed in an another branch, so there should these kind of bugs solved.

**Comment by mboom** [comment]
Although, the game does not work well. There are serious issues somewhere in the code that have to be solved.

**Comment by mboom** [comment]
It seems there is a timer issue, should be solved in the strategy pattern

**Comment by jannelie** [comment]
game crasht niet meer.
save and resume should be solved by the change to json
next level issue should be solved with the strategy pattern
So this branch is ready for merging!

**Pull request merged**
